#!/usr/bin/env bash

set -euo pipefail

bazel_version=$(
    "${BAZEL_REAL}" --version | (
        read -r -a v
        echo "${v[1]}"
    )
)

# enable config per each major version, i.e. bazel6, bazel7, bazel8, ...
config="--config=bazel${bazel_version%%.*}"

declare -a args=()

while [ "$#" -gt 0 ]; do
    option="$1"
    if [[ "$option" = -* ]]; then
        args+=( "$option" )
        shift
    else
        break
    fi
done

if [ "$#" -gt 0 ]; then
  command="$1" ; shift
  args+=( "$command" "$config" "$@" )
elif [ "${#args[@]}" -eq 0 ]; then
  # no startup options, no command
  exec "$BAZEL_REAL"
fi

exec "$BAZEL_REAL" "${args[@]}"
