name: Execute Bazel test
description: Handles platform-specific settings.

inputs:
  working-directory:
    type: string
  os:
    type: string

runs:
  using: composite
  steps:
    - shell: bash
      env:
        BAZEL_SH: ${{ startswith(inputs.os, 'windows-') && 'C:\msys64\usr\bin\bash.exe' || '' }}
        RBT_WORKING_DIR: ${{ inputs.working-directory }}
      run: |
        [[ "${RBT_WORKING_DIR:-}" != "" ]] && cd "${RBT_WORKING_DIR}"
        bazel test "//..."

