# Create a draft release when triggered via Github's UI or Github CLI
name: Prepare Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (e.g. 0.11.0)'
        required: true
        type: string

permissions:
  contents: write

jobs:
  release:
    name: Prepare Release
    runs-on: ubuntu-latest
    steps:
      - name: Check version
        run: |
          if ! [[ '${{ inputs.version }}' =~ ^[0-9]+[.][0-9]+[.][0-9]+$ ]]; then
             echo '${{ inputs.version }} does not match expected format `major.minor.patch`' >&2
             exit 1
           fi
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          ref: master           # only create releases from main branch
      - name: Read section from CHANGELOG.md
        id: extract-changelog
        uses: sean0x42/markdown-extract@7b185cbe85263116bbf741e739e7198ba86465dc # v2.1.0
        with:
         file: CHANGELOG.md
         pattern: ${{ inputs.version }}
      - name: Prepare release notes and artifacts
        id: prepare
        run: |
          .github/workflows/release_prep.sh v${{ inputs.version }} > release_notes.txt
          printf '${{ steps.extract-changelog.outputs.markdown }}' >> release_notes.txt
      - name: Create draft release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create \
            --draft \
            --notes-file release_notes.txt \
            --title v${{ inputs.version }} \
            v${{ inputs.version }} \
            ${{ steps.prepare.outputs.archive }}
