name: Continuous integration
on:
  push:
    branches: master
  pull_request:
    branches: master
  workflow_dispatch: # allows manual triggering
  schedule:
    - cron: '1 11 * * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

jobs:
  build-and-test:
    name: Build & Test
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, macos-15, windows-2025]
        bazel_mode: [workspace, module]
        version: ["7.7.1", "8.6.0"]
    defaults:
      run:
        shell: bash
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: tweag/configure-bazel-remote-cache-auth@144b0b915f13a418f5eafe2f68d19564ec136c62 # v0.1.1
        with:
          buildbuddy_api_key: ${{ secrets.BUILDBUDDY_API_KEY }}
          bazelrc_path: .bazelrc.auth
      - uses: extractions/netrc@c3879108aae6b4ed5c4eb60854ae04f06d2f2f68 # v3.0.0
        with:
          machine: api.github.com
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Configure for CI
        uses: tweag/write-bazelrc@b1f117f25f2042ecdc708026eadd23bf825bc98a # v0.1.1
        with:
          content: build --config=ci
      - name: Disable stardoc
        # Windows: Stardoc complains about docstring quote indentation on Windows.
        # bzlmod: Stardoc does not work with bzlmod.
        if: ${{ runner.os == 'Windows' || matrix.bazel_mode == 'module' }}
        uses: tweag/write-bazelrc@b1f117f25f2042ecdc708026eadd23bf825bc98a # v0.1.1
        with:
          content: build --config=no-stardoc
      - name: Enable bzlmod & disable workspace
        uses: tweag/write-bazelrc@b1f117f25f2042ecdc708026eadd23bf825bc98a # v0.1.1
        if: ${{ matrix.bazel_mode == 'module' }}
        with:
          content: build --enable_bzlmod --noenable_workspace
      - name: Enable workspace & disable bzlmod 
        uses: tweag/write-bazelrc@b1f117f25f2042ecdc708026eadd23bf825bc98a # v0.1.1
        if: ${{ matrix.bazel_mode == 'workspace' }}
        with:
          content: build --enable_workspace --noenable_bzlmod
      - name: Configure the Bazel version
        run: |
          echo "USE_BAZEL_VERSION=${{ matrix.version }}" > .bazeliskrc
          echo "USE_BAZEL_VERSION=${{ matrix.version }}" > tests/.bazeliskrc
      - name: Run Bazel test at the root
        if: ${{ matrix.bazel_mode == 'workspace' && runner.os != 'Windows' }}
        uses: ./.github/actions/run_bazel_test
      - name: Run Bazel test under the tests directory
        uses: ./.github/actions/run_bazel_test
        with:
          working-directory: tests

  all_ci_tests:
    runs-on: ubuntu-latest
    needs:
      - build-and-test
    if: ${{ always() }}
    steps:
      - uses: cgrindel/gha_join_jobs@605424defceef3181c9fde3df903ea8ec35e267a # v1.5.0
        env:
          USE_BAZEL_VERSION: '7.x'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
